---
title: "Bayesian individual participant data meta analysis"
author: "Michael Seo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Bayesian network meta-analysis}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this vignette, we describe how to run a Bayesian individual participant data meta-analysis model using this package.


```{r, eval = FALSE}
# If above doesn't work we can try by first find correct method and prediction matrix and
# then using ipdma.impute using these obtained objects. Through this process, we can check if there is any errors
# in setting up these objects.
missP <- findMissingPattern(mydata, covariates = c("baseline", "gender"), typeofvar = c("continuous", "binary"), 
                            studyname = "study",  treatmentname = "treat", outcomename = "y")
correctMeth <- getCorrectMeth(mydata, missP)
correctPred <- getCorrectPred(mydata, missP)
imputations_test <- ipdma.impute(mydata, covariates = c("baseline", "gender"), typeofvar = c("continuous", "binary"),
                             interaction = TRUE, meth = correctMeth, pred = correctPred,
                             studyname = "study", treatmentname = "treat", outcomename = "y")

```
